# -*- encoding: utf-8 -*-

=begin
#Moderation API

#API for automated content moderation

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "moderation_api/version"

Gem::Specification.new do |s|
  s.name        = "moderation_api"
  s.version     = ModerationAPI::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Moderation API"]
  s.email       = ["info@moderationapi.com"]
  s.homepage    = "https://moderationapi.com"
  s.summary     = "A Ruby SDK for the Moderation API - content moderation, PII detection, and text analysis"
  s.description = "Automatically moderate your content with Moderation API"
  s.license     = "MIT"
  s.required_ruby_version = ">= 3.0"
  s.metadata    = {
    "homepage_uri" => "https://moderationapi.com",
    "source_code_uri" => "https://github.com/yourusername/moderation_api",
    "documentation_uri" => "https://moderationapi.com/docs"
  }

  s.add_runtime_dependency 'faraday', '>= 1.0.1', '< 3.0'
  s.add_runtime_dependency 'faraday-multipart'
  s.add_runtime_dependency 'marcel'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
