=begin
#Moderation API

#API for automated content moderation

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for ModerationAPI::QueueActionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'QueueActionsApi' do
  before do
    # run before each test
    @api_instance = ModerationAPI::QueueActionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of QueueActionsApi' do
    it 'should create an instance of QueueActionsApi' do
      expect(@api_instance).to be_instance_of(ModerationAPI::QueueActionsApi)
    end
  end

  # unit tests for actions_create
  # Create an action
  # Create an action.
  # @param actions_create_request 
  # @param [Hash] opts the optional parameters
  # @return [ActionsList200ResponseInner]
  describe 'actions_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for actions_delete
  # Delete an action
  # Delete an action and all of its webhooks.
  # @param id The ID of the action to delete.
  # @param [Hash] opts the optional parameters
  # @return [ActionsDelete200Response]
  describe 'actions_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for actions_execute
  # Execute an action
  # Execute an action on a set of content items in a queue.
  # @param actions_execute_request 
  # @param [Hash] opts the optional parameters
  # @return [ActionsExecute200Response]
  describe 'actions_execute test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for actions_execute_deprecated
  # Execute an action
  # Execute an action on a set of content items in a queue.
  # @param action_id The ID or key of the action to execute.
  # @param actions_execute_deprecated_request 
  # @param [Hash] opts the optional parameters
  # @return [ActionsExecute200Response]
  describe 'actions_execute_deprecated test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for actions_get
  # Get an action
  # Get an action by ID.
  # @param id The ID of the action to get.
  # @param [Hash] opts the optional parameters
  # @return [ActionsGet200Response]
  describe 'actions_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for actions_list
  # List actions
  # List actions for the current user.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :queue_id Only return actions available in this queue.
  # @return [Array<ActionsList200ResponseInner>]
  describe 'actions_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for actions_update
  # Update an action
  # Update an action.
  # @param id The ID of the action to update.
  # @param actions_update_request 
  # @param [Hash] opts the optional parameters
  # @return [ActionsList200ResponseInner]
  describe 'actions_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
