=begin
#Moderation API

#API for automated content moderation

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ModerationApi::ActionsList400ResponseIssuesInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ModerationApi::ActionsList400ResponseIssuesInner do
  let(:instance) { ModerationApi::ActionsList400ResponseIssuesInner.new }

  describe 'test an instance of ActionsList400ResponseIssuesInner' do
    it 'should create an instance of ActionsList400ResponseIssuesInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(ModerationApi::ActionsList400ResponseIssuesInner)
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
