=begin
#Moderation API

#API for automated content moderation

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ModerationAPI::ActionsList200ResponseInnerPossibleValuesInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ModerationAPI::ActionsList200ResponseInnerPossibleValuesInner do
  let(:instance) { ModerationAPI::ActionsList200ResponseInnerPossibleValuesInner.new }

  describe 'test an instance of ActionsList200ResponseInnerPossibleValuesInner' do
    it 'should create an instance of ActionsList200ResponseInnerPossibleValuesInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(ModerationAPI::ActionsList200ResponseInnerPossibleValuesInner)
    end
  end

  describe 'test attribute "value"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
