=begin
#Moderation API

#API for automated content moderation

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ModerationAPI::ModerationText200ResponseAllOfToxicity
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ModerationAPI::ModerationText200ResponseAllOfToxicity do
  let(:instance) { ModerationAPI::ModerationText200ResponseAllOfToxicity.new }

  describe 'test an instance of ModerationText200ResponseAllOfToxicity' do
    it 'should create an instance of ModerationText200ResponseAllOfToxicity' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(ModerationAPI::ModerationText200ResponseAllOfToxicity)
    end
  end

  describe 'test attribute "label_scores"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "label"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "score"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "error"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "warning"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
