=begin
#Moderation API

#API for automated content moderation

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ModerationApi::ModerationText200ResponseAllOfNsfwLabelScores
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ModerationApi::ModerationText200ResponseAllOfNsfwLabelScores do
  let(:instance) { ModerationApi::ModerationText200ResponseAllOfNsfwLabelScores.new }

  describe 'test an instance of ModerationText200ResponseAllOfNsfwLabelScores' do
    it 'should create an instance of ModerationText200ResponseAllOfNsfwLabelScores' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(ModerationApi::ModerationText200ResponseAllOfNsfwLabelScores)
    end
  end

  describe 'test attribute "sensitive"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "unsafe"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "neutral"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
