=begin
#Moderation API

#API for automated content moderation

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ModerationApi::ModerationText200ResponseAllOfProprietyLabelScores
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ModerationApi::ModerationText200ResponseAllOfProprietyLabelScores do
  let(:instance) { ModerationApi::ModerationText200ResponseAllOfProprietyLabelScores.new }

  describe 'test an instance of ModerationText200ResponseAllOfProprietyLabelScores' do
    it 'should create an instance of ModerationText200ResponseAllOfProprietyLabelScores' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(ModerationApi::ModerationText200ResponseAllOfProprietyLabelScores)
    end
  end

  describe 'test attribute "flirtation"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "sexually_explicit"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "neutral"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
