=begin
#Moderation API

#API for automated content moderation

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ModerationAPI::ModerationObjectRequestValue
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ModerationAPI::ModerationObjectRequestValue do
  let(:instance) { ModerationAPI::ModerationObjectRequestValue.new }

  describe 'test an instance of ModerationObjectRequestValue' do
    it 'should create an instance of ModerationObjectRequestValue' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(ModerationAPI::ModerationObjectRequestValue)
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["profile", "event", "product", "object", "unknown_default_open_api"])
      # validator.allowable_values.each do |value|
      #   expect { instance.type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
