=begin
#Moderation API

#API for automated content moderation

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

# Common files
require 'moderation_api/api_client'
require 'moderation_api/api_error'
require 'moderation_api/version'
require 'moderation_api/configuration'

# Models
ModerationAPI.autoload :AccountGet200Response, 'moderation_api/models/account_get200_response'
ModerationAPI.autoload :AccountGet200ResponseCurrentProject, 'moderation_api/models/account_get200_response_current_project'
ModerationAPI.autoload :ActionsCreateRequest, 'moderation_api/models/actions_create_request'
ModerationAPI.autoload :ActionsCreateRequestWebhooksInner, 'moderation_api/models/actions_create_request_webhooks_inner'
ModerationAPI.autoload :ActionsDelete200Response, 'moderation_api/models/actions_delete200_response'
ModerationAPI.autoload :ActionsExecute200Response, 'moderation_api/models/actions_execute200_response'
ModerationAPI.autoload :ActionsExecuteDeprecatedRequest, 'moderation_api/models/actions_execute_deprecated_request'
ModerationAPI.autoload :ActionsExecuteRequest, 'moderation_api/models/actions_execute_request'
ModerationAPI.autoload :ActionsGet200Response, 'moderation_api/models/actions_get200_response'
ModerationAPI.autoload :ActionsGet200ResponseWebhooksInner, 'moderation_api/models/actions_get200_response_webhooks_inner'
ModerationAPI.autoload :ActionsList200ResponseInner, 'moderation_api/models/actions_list200_response_inner'
ModerationAPI.autoload :ActionsList200ResponseInnerPossibleValuesInner, 'moderation_api/models/actions_list200_response_inner_possible_values_inner'
ModerationAPI.autoload :ActionsList400Response, 'moderation_api/models/actions_list400_response'
ModerationAPI.autoload :ActionsList400ResponseIssuesInner, 'moderation_api/models/actions_list400_response_issues_inner'
ModerationAPI.autoload :ActionsUpdateRequest, 'moderation_api/models/actions_update_request'
ModerationAPI.autoload :ModerationAudioRequest, 'moderation_api/models/moderation_audio_request'
ModerationAPI.autoload :ModerationImage200Response, 'moderation_api/models/moderation_image200_response'
ModerationAPI.autoload :ModerationImage200ResponseLabelsInner, 'moderation_api/models/moderation_image200_response_labels_inner'
ModerationAPI.autoload :ModerationImageRequest, 'moderation_api/models/moderation_image_request'
ModerationAPI.autoload :ModerationObject200Response, 'moderation_api/models/moderation_object200_response'
ModerationAPI.autoload :ModerationObject200ResponseAllOfEntitiesInner, 'moderation_api/models/moderation_object200_response_all_of_entities_inner'
ModerationAPI.autoload :ModerationObject200ResponseAllOfFieldsInner, 'moderation_api/models/moderation_object200_response_all_of_fields_inner'
ModerationAPI.autoload :ModerationObject200ResponseAllOfLabelsInner, 'moderation_api/models/moderation_object200_response_all_of_labels_inner'
ModerationAPI.autoload :ModerationObjectRequest, 'moderation_api/models/moderation_object_request'
ModerationAPI.autoload :ModerationObjectRequestValue, 'moderation_api/models/moderation_object_request_value'
ModerationAPI.autoload :ModerationObjectRequestValueDataValue, 'moderation_api/models/moderation_object_request_value_data_value'
ModerationAPI.autoload :ModerationText200Response, 'moderation_api/models/moderation_text200_response'
ModerationAPI.autoload :ModerationText200ResponseAllOfAddress, 'moderation_api/models/moderation_text200_response_all_of_address'
ModerationAPI.autoload :ModerationText200ResponseAllOfEmail, 'moderation_api/models/moderation_text200_response_all_of_email'
ModerationAPI.autoload :ModerationText200ResponseAllOfName, 'moderation_api/models/moderation_text200_response_all_of_name'
ModerationAPI.autoload :ModerationText200ResponseAllOfNsfw, 'moderation_api/models/moderation_text200_response_all_of_nsfw'
ModerationAPI.autoload :ModerationText200ResponseAllOfNsfwLabelScores, 'moderation_api/models/moderation_text200_response_all_of_nsfw_label_scores'
ModerationAPI.autoload :ModerationText200ResponseAllOfPhone, 'moderation_api/models/moderation_text200_response_all_of_phone'
ModerationAPI.autoload :ModerationText200ResponseAllOfProfanity, 'moderation_api/models/moderation_text200_response_all_of_profanity'
ModerationAPI.autoload :ModerationText200ResponseAllOfPropriety, 'moderation_api/models/moderation_text200_response_all_of_propriety'
ModerationAPI.autoload :ModerationText200ResponseAllOfProprietyLabelScores, 'moderation_api/models/moderation_text200_response_all_of_propriety_label_scores'
ModerationAPI.autoload :ModerationText200ResponseAllOfQuality, 'moderation_api/models/moderation_text200_response_all_of_quality'
ModerationAPI.autoload :ModerationText200ResponseAllOfQualityLabelScores, 'moderation_api/models/moderation_text200_response_all_of_quality_label_scores'
ModerationAPI.autoload :ModerationText200ResponseAllOfRequest, 'moderation_api/models/moderation_text200_response_all_of_request'
ModerationAPI.autoload :ModerationText200ResponseAllOfSensitive, 'moderation_api/models/moderation_text200_response_all_of_sensitive'
ModerationAPI.autoload :ModerationText200ResponseAllOfSentiment, 'moderation_api/models/moderation_text200_response_all_of_sentiment'
ModerationAPI.autoload :ModerationText200ResponseAllOfSentimentLabelScores, 'moderation_api/models/moderation_text200_response_all_of_sentiment_label_scores'
ModerationAPI.autoload :ModerationText200ResponseAllOfToxicity, 'moderation_api/models/moderation_text200_response_all_of_toxicity'
ModerationAPI.autoload :ModerationText200ResponseAllOfToxicityLabelScores, 'moderation_api/models/moderation_text200_response_all_of_toxicity_label_scores'
ModerationAPI.autoload :ModerationText200ResponseAllOfUrl, 'moderation_api/models/moderation_text200_response_all_of_url'
ModerationAPI.autoload :ModerationText200ResponseAllOfUsername, 'moderation_api/models/moderation_text200_response_all_of_username'
ModerationAPI.autoload :ModerationText200ResponseAllOfWordlist, 'moderation_api/models/moderation_text200_response_all_of_wordlist'
ModerationAPI.autoload :ModerationText200ResponseAllOfWordlistsInner, 'moderation_api/models/moderation_text200_response_all_of_wordlists_inner'
ModerationAPI.autoload :ModerationTextRequest, 'moderation_api/models/moderation_text_request'
ModerationAPI.autoload :ModerationVideo200Response, 'moderation_api/models/moderation_video200_response'
ModerationAPI.autoload :ModerationVideoRequest, 'moderation_api/models/moderation_video_request'

# APIs
ModerationAPI.autoload :AccountApi, 'moderation_api/api/account_api'
ModerationAPI.autoload :ModerateApi, 'moderation_api/api/moderate_api'
ModerationAPI.autoload :QueueActionsApi, 'moderation_api/api/queue_actions_api'

module ModerationAPI
  class << self
    # Customize default settings for the SDK using block.
    #   ModerationAPI.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
